version: '3.9'
services:
  server:
    container_name: app_server
    build: ./server
    ports:
      - 3001:3001
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env
    environment:
      - MYSQL_HOST=db
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores